In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("C:/Users/HP/Downloads/archive (10)/House_Rent_Dataset.csv")

In [4]:
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [5]:
df.head(10)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
5,2022-04-29,2,7000,600,Ground out of 1,Super Area,Thakurpukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
6,2022-06-21,2,10000,700,Ground out of 4,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,2,Contact Agent
7,2022-06-21,1,5000,250,1 out of 2,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,1,Contact Agent
8,2022-06-07,2,26000,800,1 out of 2,Carpet Area,"Palm Avenue Kolkata, Ballygunge",Kolkata,Unfurnished,Bachelors,2,Contact Agent
9,2022-06-20,2,10000,1000,1 out of 3,Carpet Area,Natunhat,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner

In [6]:
df.isnull().sum()

Posted On            0
BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

In [7]:
x = df.iloc[: , [1,3,6,7,8,10]]

In [8]:
x

,BHK,Size,Area Locality,City,Furnishing Status,Bathroom
0,2,1100,Bandel,Kolkata,Unfurnished,2
1,2,800,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,1
2,2,1000,Salt Lake City Sector 2,Kolkata,Semi-Furnished,1
3,2,800,Dumdum Park,Kolkata,Unfurnished,1
4,2,850,South Dum Dum,Kolkata,Unfurnished,1
...,...,...,...,...,...,...
4741,2,1000,Bandam Kommu,Hyderabad,Semi-Furnished,2
4742,3,2000,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,3
4743,3,1750,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,3
4744,3,1500,Gachibowli,Hyderabad,Semi-Furnished,2
4745,2,1000,Suchitra Circle,Hyderabad,Unfurnished,2

In [9]:
y = df.iloc[: , [-10]]

In [10]:
num_cols = ['BHK', 'Size', 'Bathroom']
cat_cols = ['Area Locality','City','Furnishing Status']

In [11]:
y

       Rent
0     10000
1     20000
2     17000
3     10000
4      7500
...     ...
4741  15000
4742  29000
4743  35000
4744  45000
4745  15000

[4746 rows x 1 columns]

In [12]:
import sklearn

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.2 , random_state = 42)

In [15]:
y_test

       Rent
1566  16000
3159  12000
538   28000
2630   8000
4418  46000
...     ...
4124  18000
3400  25000
1941  14000
3679  26000
2531  11000

[950 rows x 1 columns]

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [17]:
from sklearn.pipeline import Pipeline

In [18]:
# Numerical pipeline
num_transformer = Pipeline(steps=[('standardize', StandardScaler())])

In [19]:
# Categorical pipeline
cat_transformer = Pipeline(steps=[('encode' , OneHotEncoder(handle_unknown='ignore'))])

In [20]:
# Column Transformer
transformer1 = ColumnTransformer(transformers=[('numerical1' , num_transformer , num_cols),
                                              ('categorical2' , cat_transformer , cat_cols)])

In [21]:
from sklearn.ensemble import RandomForestRegressor

In [22]:
# Final pipeline
model = Pipeline(steps=[
    ('transfomer' , transformer),
    ('regressor', RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ))

])

In [23]:
# Train model
model.fit(x_train, y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Pipeline(steps=[('transfomer',
                 ColumnTransformer(transformers=[('numerical1',
                                                  Pipeline(steps=[('standardize',
                                                                   StandardScaler())]),
                                                  ['BHK', 'Size', 'Bathroom']),
                                                 ('categorical2',
                                                  Pipeline(steps=[('encode',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Area Locality', 'City',
                                                   'Furnishing Status'])])),
                ('regressor', RandomForestRegressor(random_state=42))])

In [24]:
# Prediction
y_pred = model.predict(x_test)

In [25]:
print(y_pred)

[ 15722.          12643.54        36000.02        42720.
  49460.          14865.          38845.          13115.
 280900.          11430.           9599.          10450.
  16101.          10287.5         17200.          21985.
  95970.           8350.          12293.33        47865.
  22990.           6618.33333333  37065.          14243.
 143820.           7190.           8175.          39600.
   6902.           8752.           6771.66666667   8985.
   7765.          13585.          20080.          22359.69
   7940.           6606.66666667  16176.           7514.81066667
  13675.         311600.          15045.           6773.
  44792.73809524   9805.          36210.02        68385.
 489200.          19660.           9651.          23560.
  14900.          15445.          36210.02       189100.
  32330.          69430.           9340.          13646.
 852984.          12335.          73655.          10750.
  26539.38        18996.19047619  21525.          20105.
  35505.          20400.          13882.16666667  26540.
  57273.33333333   8011.66666667  11770.          37748.33333333
  15765.          54410.          23000.          21370.
  15355.          11620.          24607.          10283.5952381
  13185.          26900.          45323.33333333  18150.
  22135.          17610.         283700.          32580.
  36165.         143750.          14328.33        16010.
  11825.           6731.66666667  18640.          16190.
  26207.5          9741.          39182.5          8091.66666667
  11812.5          9062.           6825.          13790.
  13174.66666667   8175.          13092.66666667 127300.
 195700.          15545.          43380.         208900.
  19250.          10315.           9960.          15294.75
   8307.5         12105.         116850.          11645.
   8555.          13745.          15705.         134610.95238095
   9250.         146730.          16732.85714286 133670.
  21960.          41761.5         15445.          24535.
  14800.          16715.          27148.           7078.
  12670.80952381   6825.          18504.92        20225.
   7083.           6098.           8218.5         12750.
   4759.          44640.          21315.          67068.33333333
  45890.          10562.5         21452.93333333  12090.
  63750.          16415.          16428.          13020.
  41480.         128091.66666667   5841.          15792.
  23255.           5815.          15660.           9675.
   5753.         121436.66666667  10562.5         24445.
  31585.          12950.          32060.          17535.33333333
   6032.          10385.          20243.82         9535.
   9997.5         10785.           9840.          24650.
  75880.           6107.5         26505.          13745.
  29550.           9725.          25520.           7719.044
  12284.34        15325.          62860.          12230.
   6497.           7611.          23380.          10820.
  63590.          25465.           6606.66666667  46362.
  37135.           9290.           7002.           8120.83333333
  12860.           5497.66666667  14707.           9490.
  20205.          57972.           9340.          16725.
   6940.           7681.          17285.          49831.
   8963.          20205.          21930.          32930.
  10323.54        42800.           5062.          13305.
   8542.          10323.54        20570.          18725.
 120520.          11645.          12890.           5936.
   6674.70833333  13984.97         8380.          11993.33
  30565.          15355.           9320.          11630.
  20195.          16800.          35260.          12185.
  35045.           9840.          10187.          27240.
  27292.          14085.5         18225.          10272.
  10815.           6550.46        19110.           9340.
  12259.          11775.          37895.          32900.
  20635.          18115.         262800.          22485.
   8203.          90445.           8425.          69956.95
  10841.          11336.77        10965.          59851.
 127871.66666667  12330.          10112.2         16405.
  30975.          33066.          21505.          22609.07
 340300.          30360.          69223.          16485.
  13569.99        72003.          11955.          17290.
   8752.           5125.         123700.          12430.
  45555.          10075.          43760.          72080.
  16875.          43910.          24240.          18895.
  10046.2         49810.          68670.           6896.66666667
  12400.           7332.          11930.          16410.
  36350.          31510.          22185.          51624.98
   5605.          70555.           8095.          13305.
  66638.33333333   9595.          15480.          35760.
  17410.          13199.47619048   7785.          17486.33333333
  15062.5         65490.          70324.99        15790.
   6545.           5048.           6618.33333333   8210.
 133210.          25409.99        87461.          11575.
  12930.          44415.           5680.           6032.
  12515.          23875.          15722.           9733.33333333
 533600.          12505.          50931.          53440.
   8790.          12130.          50995.           9741.
  11819.32142857   6618.33333333  14715.         189800.
  14225.          10868.83333333  17148.74        12860.
  14425.         155120.           8445.          34170.
   5062.           7002.          17125.          53112.
   8985.          41130.          64080.           7595.86111111
  52741.           9759.33333333  31178.          17029.69
  82120.          17487.5          8690.          21066.30952381
  51274.66666667  10340.          26165.          94970.
  58646.66666667   8175.          10031.2          5827.66666667
  12480.           6788.          50570.          39560.
  17125.          10287.5        172100.          23396.61
  17580.          11085.          29540.          16480.
  33135.          21452.93333333  14580.           7078.
  11125.          20948.          27735.          37050.
  18020.          35829.69        15945.          12505.
  81050.           9441.          17185.33333333  26320.
  12905.          32050.          19470.          13675.
  25783.          20635.          13820.          17029.69
   8411.          26505.           5108.          33900.
   8447.          14460.5        120090.          13735.
  42646.83333333  26770.         133450.          16101.
  11835.           5087.          25705.          14220.
  12860.         393700.          32815.          11825.
  38685.          15065.5         29655.           7049.5
  64540.          13755.          20825.           9310.
  11710.           5123.          11140.          11641.65
  44089.16666667  10212.          10015.           8890.
  28799.01        23695.         115750.          56702.
  10070.          15998.           8174.          65110.
  19615.           7658.           6442.          10170.
  22795.          74746.66666667  19450.         147115.
  13645.           9500.          63750.          15107.5
  17574.89        13015.           9595.          69511.
   8770.          63590.           8955.          70290.
  17632.5         62160.          15442.          25560.
  16930.          14890.         400269.           7112.35066667
   7725.          12445.          39220.           9675.
  13185.          44792.73809524   9742.5         60575.
  10990.          39706.66666667  12381.66666667   6442.
  13675.          12015.           8315.           8175.
  50921.66666667  14565.5         45440.          22759.07
   5684.33333333  13450.          21315.          11955.
   6545.           6448.          11090.           7089.
  13630.          17265.          13473.25        10112.2
  70741.          55645.          16500.          33370.
  11955.          10705.          46440.           6123.
   6923.          12375.          25175.           9683.75
  37940.06        16990.          26210.          16105.
  12685.          12860.          10285.          20830.
  38280.           7514.81066667  11537.33        26210.
   8200.          15340.           9310.         212900.
  17965.          38525.          88310.          25740.
  10287.5         38800.          12900.          22670.
   6728.          25210.          16320.          10397.16666667
  11855.          16485.          15353.           8176.
   6769.          10130.          51015.          11974.22619048
  15340.          11692.          20635.          10597.5
  13510.5         69430.          33235.          18915.
  46215.         107308.33333333  22345.          10005.
  10975.          17905.          32696.66666667 176410.
  15145.          40411.25         8752.          15400.
   9120.          11090.         292700.          41526.5
   9759.2          5565.         217480.         239210.
  17135.           8780.          32245.           9286.
  62820.          37380.           5919.          25020.
   9180.          14125.          34385.           5305.
  63180.           9058.          30014.99         6618.33333333
  20305.           7023.          10110.          13158.25
 107308.33333333  33235.           4783.          10323.54
   6902.         135363.33333333 112439.04761905  10212.
  14946.5         28360.           9340.           7218.66666667
   8474.          10323.54        10323.54        10260.
 115225.           8426.           9661.           6606.66666667
  13313.          11810.           8752.          28940.74666667
  17900.          11621.65        13934.01333333  14250.
   8380.          24110.          42221.25        24438.3
  34174.38        12085.          18020.83333333   8955.
   8734.           6720.          16810.          24435.
  13725.           8955.         113435.          16685.
  13310.           7514.81066667  37435.           6071.
  19705.          10075.          22245.          17111.83333333
  39706.66666667  17595.          29990.          14370.
  15355.          23507.5         14300.           7658.
   8600.          27234.99        19705.         141320.47619048
   7601.          10005.          20940.          10283.5952381
 123165.         199533.33333333  11518.33        10385.
   7775.          33113.33333333   8752.          28559.97
  31405.          32230.           7400.          20854.97
  12270.           7830.           5680.           9840.
   9325.          10957.5          6771.66666667  49831.
 137603.33333333  72080.          11127.5         12880.
  14260.           4607.66666667 142260.           8175.
  17095.          17432.5         18185.          13825.
  59940.          14040.           7314.          12805.
  15470.           7033.          11320.           6093.
  43650.          14905.          13566.          10015.
 218600.          10046.77        16105.          12530.
 124690.          31720.           7457.         217800.
  37380.         170150.           8752.          12302.
  66367.          32864.97        51245.          12640.25
   8926.           5680.          11470.          16925.
  10385.           5613.          10008.           6956.
   5114.          11205.          68090.           8800.
  14115.          24997.5         59570.          12955.
  16055.          16185.          17750.          21910.
   7720.          64200.           8203.          88310.
  12171.         150360.          10540.           7118.125
   9340.          12090.          12928.           8102.
  15210.           6763.          23198.75        17930.
  92135.          17475.          18343.02         6720.
  13450.          52802.          11225.          35610.
  69820.          14955.          71500.          69500.
  10815.          13175.           7675.          14820.
   5956.           6731.66666667  49831.          40820.
  16315.66666667   9655.52777778   6550.46        23522.5
   6853.          10185.          20245.          19080.
  10227.          15380.         215700.          25335.
  10562.5         11799.33         6956.           9471.
  10255.         125533.33333333  42750.          28640.
  25035.          35100.          30935.          28134.07
  79206.          29335.          15998.          68190.
  16050.         154813.33333333 168933.33333333  35910.
  15820.          11538.75         7150.          13359.99
  20685.           9225.          15420.          12840.
   6590.          10211.33333333   9408.75        36315.
  38711.66666667  15788.           6683.66666667  12875.75
  14575.           7795.           6415.         128790.
  10766.66        10449.          40350.           9915.
  23905.           9249.           8985.           9551.
   5074.          32330.          13185.          12038.84
   8155.          17780.          36480.          13160.
   6217.          12123.33        28685.         230700.
  18930.          13470.          17595.          17050.
  42895.          12165.           8450.          34550.
  13185.           8150.           7036.          17160.
  69211.          21085.          23380.          10815.
  22225.          12705.          27282.33        10015.
  14243.          69450.          15355.          12667.5
  61066.66666667  12650.          35755.          16435.
 137300.          19785.          31764.98        16101.
 136470.          20215.          10380.16666667  19484.98
   6614.66666667 109488.33333333  18080.          60253.
  12867.           7078.          10865.          12025.
   8846.          10080.          29590.          12600.
  20685.           9733.33333333  12935.          10910.
  15505.          50995.          12090.          19960.
  23672.5         10385.          11430.           6923.
  11945.          12670.          16830.          12525.
  16835.          10397.16666667]

In [26]:
from sklearn.metrics import r2_score

In [27]:
score = r2_score(y_test, y_pred)
print(score)

0.512689094042069